# Update your supabase/config.toml with these settings

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://127.0.0.1:3000", "http://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6

# DISABLE EMAIL CONFIRMATION FOR DEVELOPMENT
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false  # This disables email confirmation
max_frequency = "1s"
otp_exp = 86400
otp_length = 6

# Keep your existing external providers
[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://localhost:3000/auth/callback"

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_CLIENT_SECRET)"
redirect_uri = "http://localhost:3000/auth/callback"